# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVmhOvsLg1IStZnboef_WdSQeT8tMVGd
"""

#importing libraries
import json
import string
import random

import nltk
import numpy as np
from nltk.stem import WordNetLemmatizer

import nltk
nltk.download('punkt')


import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout

nltk.download("punkt")
nltk.download("wordnet")
nltk.download("wordnetlemmatizer")

data={"intents":[
    {"tag":"greetings",
    "patterns":["Hello","How are you?","hi"],
    "reponses":["Howdy ppartner!","Hello","How are you doing?","Greetings"]
    },

    {"tag":"age",
    "patterns":["How old are you","when is your birthday","when was you born"],
    "reponses":["I am 25 years old","I was born in 1996","My birthday is july 3rd","03/07/1996"]
    },

    {"tag":"date",
    "patterns":["what are you doing this weekend","do you want to hangout sometime?","what are your plans for this week"],
    "reponses":["I am available this week","I don't have any plans","I am not busy"]
    },

     {"tag":"name",
    "patterns":["what's your name","what are you called","who are you"],
    "reponses":["My name is Mort","I'm Mort","Mort"]
    },

     {"tag":"goodbye",
    "patterns":["bye","g2g","see ya","adios","cya"],
    "reponses":["It was nice speaking to you","see you later","speak soon"]
    },

]}

#initialising lemmatier to get stem of words
lemmatizer=WordNetLemmatizer

words=[]
classes=[]
doc_x=[]
doc_y=[]

for intent in data["intents"]:
    for pattern in intent["patterns"]:
        tokens=nltk.word_tokenize(pattern)
        words.extend(tokens)
        doc_x.append(pattern)
        doc_y.append(intent["tag"])
    if  intent["tag"]not in classes:
        classes.append(intent["tag"])

words=[lemmatizer.lemmatize(word.lower())for word in words if word not in string.punctuation]
words[ :10]

words=sorted(set(words))
classes=(sorted(set(classes)))

print(words)

print(classes)

print(doc_x)

print(doc_y)

training=[]
out_empty=[0]*len(classes)

#creating a bag of words model

for idx,doc in enumerate(doc_x):
    bow=[]
    text=lemmatizer.lemmatize(doc.lower())
    for word in words:
        bowappend(1)if word in text else bowappend(0)
    output_row=list(out_empty)
    output_row[classesindex(doc_y[idx])]=1

    trainingappend([bow,output_row])

random.shuffle(training)

training=np.array(training,dtype=object)

train_x=np.array(list(training[:0]))
train_y=np.array(list(training[:1]))

input_shape=(len(train_x[0]),)
output_shape=len(train_y[0])


epochs=500

model=Sequential()
model.add(Dense(128, input_shape=input_shape,activation='relu'))
model.add(Dropout(0.5))
modeladd(Dense(64,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(output_shape,activation='softmax'))
adam=tf.keras.optimizers.Adam(learning_rate=0.01,decay=1e-6)

modelcompile(lovv='categorical_crossentropy',
            optimizer="adam",
            metrics="accuracy")
print(modelsummary())

modelfit(x=train_x,y=train_y,epochs=500,verbose=1)

def clean_text(text):
    tokens=nltk.word_tokenize(text)
    tokens=[lemmatizer.lemmatize(word)for word in tokens]
    return tokens

def bag_of_words(text,vocab):
    tokens=clean_text(text)
    bow=[0]*len(vocab)
    for w in tokens:
        for idx,word in enumerate(vocab):
            if word==w:
                bow[idx]=1
        return np.array(bow)

def pred_class(text,vocab,labels):
    bow=bag_of_words(text,vocab)
    result=model.predict(np.array([bow]))[0]
    thres=0.2
    y_pred=[[idx,res] for idx,res in enumerate(result) if res>thresh]

    y_pred.sort(key=lambda x:x[1],reverse=True)
    return_list=[]
    for r in y_pred:
        return_livt.append(labels[r[0]])
    return return_list

def get_response(intents_list,intents_json):
    tag=intents_list[0]
    list_of_intents=intents_json["intents"]
    for i in list_of_intents:
        if i["tag"]==tag:
            result=random.choice(i["responses"])
            break
        return result

while True:
    message=input("")
    intents=pred_class(message,words,classes)
    result=get_response(intents,data)
    print(result)

